#!/bin/bash
# borders configuration
# Symlinked to ~/.config/borders/bordersrc
# Docs: https://github.com/FelixKratz/borders

options=(
    active_color="glow(0xff44d4e8)" # bold cyan glow
    inactive_color=0xff494d64 # muted purple — Dracula selection
    width=8.0
)

borders "${options[@]}"
